dependencies:
  - aave/protocol-v2@1.0.1

compiler:
  solc:
    remappings:
      - '@aave=aave/protocol-v2@1.0.1'

dotenv: .env

networks:
  default: mainnet-fork
  # for testnets, Aave uses different versions of the token (e.g. testnet Dai), for liquidity reasons.
  # we cannot use the standard DAI testnet address -> use Aave's testnet Dai address
  # refer to v3 for rinkeby
  rinkeby: 
    weth_token: '0xc778417E063141139Fce010982780140Aa0cD5Ab'  #WEthGateway contract
    lending_pool_addressess_provider: '0x88757f2f99175387ab4c6a4b3067c77a695b0349'
    dai_eth_price_feed: '	0x74825DbC8BF76CC4e9494d0ecB210f676Efa001D'
    dai_token_address: '0x0F48c09701B6D24d6D9571637758EE06eeCb9630'
    verify: True

  kovan:
    weth_token: '0xd0A1E359811322d97991E03f863a0C30C2cF029C'  #WEthGateway contract
    lending_pool_addressess_provider: '0x88757f2f99175387ab4c6a4b3067c77a695b0349'
    dai_eth_price_feed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
    dai_token_address: '0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD'
    verify: True
  
  mainnet-fork: #development env, fork uses live mainnet addresses 
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'  #WEthGateway contract
    lending_pool_addressess_provider: '0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5'
    dai_eth_price_feed: '0x773616E4d11A78F511299002da57A0a94577F1f4'
    dai_token_address: '0x6B175474E89094C44Da98b954EedeAC495271d0F'

  mainnet: # for live deployment
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'  #WEthGateway contract

wallets:
  wallet1: ${PRIVATE_KEY}

